sudo: false
language: perl
matrix:
  include:
  - perl: "5.26"
    env: AUTHOR_TESTING=1
  - perl: "5.24"
    env: COVERAGE=1
  - perl: "5.22"
  - perl: "5.20"
  - perl: "5.18"
  - perl: "5.16"
  - perl: "5.14"
  - perl: "5.12"
  - perl: "5.10"
notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
before_install:
  - eval $(curl https://travis-perl.github.io/init) --perl
install:
  - cpanm App::cpm
  - cpm install -g --with-develop --with-suggests
  - cpan-install --coverage   # installs coverage prereqs, if enabled
cache:
  directories:
    - ~/perl5
before_script:
  - coverage-setup
script:
  - prove -lr -j$(test-jobs) t
after_success:
  - coverage-report
env:
  global:
    - AUTHOR_TESTING=0
    - COVERAGE=0
